# Generated by Django 4.0 on 2025-11-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='badge_rank',
            field=models.CharField(choices=[('bronze', '銅バッジ'), ('silver', '銀バッジ'), ('gold', '金バッジ'), ('rainbow', '虹バッジ')], default='bronze', max_length=10, verbose_name='バッジランク'),
        ),
    ]
