# Generated by Django 4.0 on 2026-01-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_badge_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='badge_rank',
            field=models.CharField(choices=[('none', 'なし'), ('bronze', '銅バッジ'), ('silver', '銀バッジ'), ('gold', '金バッジ'), ('rainbow', '虹バッジ')], default='none', max_length=10, verbose_name='バッジランク'),
        ),
    ]
