# Generated by Django 4.0 on 2025-11-13 00:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='タグ名')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
            },
        ),
        migrations.CreateModel(
            name='PhotoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', '新規'), ('in_progress', '対応中'), ('completed', '対応完了'), ('not_required', '対応不可')], default='new', max_length=20, verbose_name='対応状況')),
                ('priority', models.CharField(choices=[('none', '--'), ('low', '低'), ('medium', '中'), ('high', '高')], default='none', max_length=20, verbose_name='対応優先順位')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='管理者メモ/対応内容')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='タイトル')),
                ('comment', models.TextField(blank=True, verbose_name='詳細コメント')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='写真')),
                ('latitude', models.DecimalField(blank=True, decimal_places=25, max_digits=30, null=True, verbose_name='緯度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=25, max_digits=30, null=True, verbose_name='経度')),
                ('location_name', models.CharField(blank=True, max_length=255, verbose_name='地名')),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時')),
                ('tags', models.ManyToManyField(related_name='photo_posts', to='main.Tag', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '写真投稿',
                'verbose_name_plural': '写真投稿',
                'ordering': ['-posted_at'],
            },
        ),
    ]
