# Generated by Django 4.0 on 2025-11-19 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photopost',
            name='location_name',
        ),
    ]
