# Generated by Django 4.0 on 2025-11-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_photopost_latitude_alter_photopost_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopost',
            name='title',
            field=models.CharField(default='タイトルなし', max_length=100, verbose_name='タイトル'),
            preserve_default=False,
        ),
    ]
