# Generated by Django 4.0 on 2025-11-19 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_photopost_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photopost',
            name='tags',
        ),
        migrations.AddField(
            model_name='photopost',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_posts', to='main.tag', verbose_name='メインカテゴリ'),
        ),
    ]
