# Generated by Django 4.0 on 2025-11-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_photopost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopost',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='経度'),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='priority',
            field=models.CharField(choices=[('not', '--'), ('low', '低'), ('medium', '中'), ('high', '高')], default='not', max_length=20, verbose_name='対応優先順位'),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='タイトル'),
        ),
    ]
