# Generated by Django 4.0 on 2025-11-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_photopost_latitude_alter_photopost_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopost',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True, verbose_name='経度'),
        ),
    ]
