# Generated by Django 4.0 on 2025-11-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_photopost_latitude_alter_photopost_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopost',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, verbose_name='経度'),
        ),
    ]
