# Generated by Django 4.0 on 2025-11-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_photopost_latitude_alter_photopost_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopost',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=30, null=True, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=30, null=True, verbose_name='経度'),
        ),
    ]
