# Generated by Django 4.0 on 2025-11-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_photopost_latitude_alter_photopost_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopost',
            name='priority',
            field=models.CharField(choices=[('none', '--'), ('low', '低'), ('medium', '中'), ('high', '高')], default='none', max_length=20, verbose_name='対応優先順位'),
        ),
    ]
